spring.application.name=MATCH-SERVICE
server.port=8083

# =========================
# Eureka
# =========================
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# =========================
# Database (container ? host)
# =========================
spring.datasource.url=jdbc:mysql://mysql:3306/Indichess_db
spring.datasource.username=root
spring.datasource.password=Reddy@2003PP
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# =========================
# User Service (via Gateway)
# =========================
user.service.url=http://api-gateway:8080

# =========================
# Logging
# =========================
logging.level.org.springframework.messaging=INFO
logging.level.org.springframework.web.socket=WARN
logging.level.com.Match_Service=DEBUG


eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90
