spring.application.name=Eureka-Server
server.port=8761

# Eureka Server: do not register itself or fetch registry from itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Optional: allow all origins for local dev dashboard
spring.web.cors.allowed-origins=*